BEGIN;

/* Drop du domain email qui lors d'un droptable emepeche le bon fonctionnement */
DROP DOMAIN IF EXISTS "email" CASCADE;

/* Création du domaine "email" avec un regex pour valider les adresses email */
CREATE DOMAIN "email" AS text CHECK (
    value ~ '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
);

/* Création de la table "role" */
CREATE TABLE "role" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(12)
);

/* Création de la table "category" */
CREATE TABLE "category" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL
);

/* Création de la table "user" */
CREATE TABLE "user" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" "email" NOT NULL UNIQUE,
    "password" VARCHAR NOT NULL,
    "username" VARCHAR(15) NOT NULL,
    "biography" VARCHAR(255) DEFAULT NULL,
    "role_id" INTEGER DEFAULT 2 REFERENCES "role"("id")
);

/* Création de la table "stretch" */
CREATE TABLE "stretch" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(255) NOT NULL,
    "description_content" TEXT NOT NULL,
    "main_image" VARCHAR DEFAULT NULL,
    "description_image" VARCHAR DEFAULT NULL,
    "category_id" INTEGER REFERENCES "category"("id")
);

/* Création de la table de jointure "user_stretch" pour la relation N,N entre "user" et "stretch" */
CREATE TABLE "user_stretch" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "stretch_id" INTEGER NOT NULL REFERENCES "stretch"("id") ON DELETE CASCADE,
    UNIQUE ("user_id", "stretch_id")
);

CREATE TABLE "category_post" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL
);

/* Création de la table "post" */
CREATE TABLE "post" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(255) NOT NULL,
    "description_content" TEXT NOT NULL,
    "category_post_id" INTEGER REFERENCES "category_post"("id")
);


/* Création de la table de jointure "user_post" pour la relation N,N entre "user" et "post" */
CREATE TABLE "user_post" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "post_id" INTEGER NOT NULL REFERENCES "post"("id") ON DELETE CASCADE,
    UNIQUE ("user_id", "post_id")
);

/* Création de la table "message" */
CREATE TABLE "message" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "texte_content" TEXT NOT NULL
);

/* Création de la table de jointure "user_message" pour la relation N,N entre "user" et "message" */
CREATE TABLE "user_message" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "message_id" INTEGER NOT NULL REFERENCES "message"("id") ON DELETE CASCADE,
    UNIQUE ("user_id", "message_id")
);

/* Création de la table de jointure "post_message" pour la relation N,N entre "post" et "message" */
CREATE TABLE "post_message" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "post_id" INTEGER NOT NULL REFERENCES "post"("id") ON DELETE CASCADE,
    "message_id" INTEGER NOT NULL REFERENCES "message"("id") ON DELETE CASCADE,
    UNIQUE ("post_id", "message_id")
);

/* Création de la table "post_category" */
CREATE TABLE "post_category" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "post_id" INTEGER NOT NULL REFERENCES "post"("id") ON DELETE CASCADE,
    "category_post_id" INTEGER NOT NULL REFERENCES "category_post"("id") ON DELETE CASCADE,
    UNIQUE ("post_id", "category_post_id")
);

COMMIT;